version: "3.7"
services:
    nginx:
        image: baijunyao/nginx:1.19
        volumes:
            - .:/app
            - ./deploy/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        environment:
            FASTCGI_PASS: php:9000
            DOCUMENT_ROOT: /app/public

    php:
        image: baijunyao/php:8.2-fpm-pgsql
        tty: true
        volumes:
            - "nfsmount:/app"
            - "composer:/root/.composer"
        environment:
            REDIS_HOST: redis
            DB_HOST: docker.for.mac.host.internal

    redis:
        image: redis:5

volumes:
    nfsmount:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3,wsize=32768,rsize=32768
            device: ":/System/Volumes/Data/${PWD}"
    composer:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3,wsize=32768,rsize=32768
            device: ":/System/Volumes/Data/Users/${LOGNAME}/.composer"
